"""add video metadata, note blocks, question enrichment

Revision ID: e244102c03cf
Revises: 822dcf8e0093
Create Date: 2026-07-19 16:36:03.931403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e244102c03cf'
down_revision: Union[str, Sequence[str], None] = '822dcf8e0093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('notes', 'content')
    op.add_column('practice_questions', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('practice_questions', sa.Column('marks', sa.Integer(), nullable=True))
    op.add_column('practice_questions', sa.Column('topic_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('practice_questions', sa.Column('timestamp_seconds', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('youtube_video_id', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('channel_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'channel_name')
    op.drop_column('videos', 'youtube_video_id')
    op.drop_column('practice_questions', 'timestamp_seconds')
    op.drop_column('practice_questions', 'topic_tags')
    op.drop_column('practice_questions', 'marks')
    op.drop_column('practice_questions', 'difficulty')
    op.add_column('notes', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'blocks')
    # ### end Alembic commands ###
